name: Generate and Upload CVs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-upload:
    permissions:
      contents: write
    name: Generate and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Generate PDFs
        run: make all

      - name: Create release for pdfs
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/*.pdf
