name: Generate and Upload CVs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-upload:
    permissions:
      contents: write
    name: Generate and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install NPM Packages
        run: npm ci

      - name: Generate LaTeX files
        run: npm start

      - name: Compile LaTeX files into pdf
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: |
            ./build/*.tex

      - name: Create release for pdfs
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./*.pdf
